In [1]:
import numpy as np

In [2]:
my_array = np.array([10,12,14,16,20,25])

print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

[10 12 14 16 20 25]
int32
4


In [3]:
my_array = np.array(["Red","Green","Orange"])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['Red' 'Green' 'Orange']
<U6
24


In [4]:
my_array = np.array(["2024-05-28", "2024-05-29", "2024-05-30"])
print (my_array)
print (my_array.dtype)
print (my_array.dtype.itemsize)

['2024-05-28' '2024-05-29' '2024-05-30']
<U10
40


# astype()

In [5]:
my_array3 = my_array.astype("M")

print(my_array3.dtype)
print(my_array3.dtype.itemsize)

datetime64[D]
8


In [6]:
my_array = np.array(["2024-05-28", "2024-05-29", "2024-05-30"], dtype= "M")

print (my_array)
print (my_array.dtype)
print (my_array.dtype.itemsize)

['2024-05-28' '2024-05-29' '2024-05-30']
datetime64[D]
8


# Array()

In [7]:
nums_list = [ 10 , 12 , 14 , 16 , 20 ]
nums_array = np.array(nums_list)
type (nums_array)

numpy.ndarray

In [8]:
row1 = [ 10 , 12 , 13 ]
row2 = [ 45 , 32 , 16 ]
row3 = [ 45 , 32 , 16 ]
nums_2d = np.array([row1, row2, row3])
nums_2d.shape

(3, 3)

# Arrange()

In [9]:
nums_arr = np.arange(5,11)
print(nums_arr)

[ 5  6  7  8  9 10]


In [10]:
nums_arr = np.arange(5,12,2)
print(nums_arr)

[ 5  7  9 11]


# Ones()

In [11]:
ones_array = np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [12]:
ones_array = np.ones((6,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Zero()

In [13]:
zeros_array = np.zeros(6)
print(zeros_array)

[0. 0. 0. 0. 0. 0.]


In [14]:
zeros_array = np.zeros((6,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Eye()

In [15]:
eyes_array = np.eye(5)
print(eyes_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Random.rand()

In [16]:
uniform_random = np.random.rand(4,5)
print(uniform_random)

[[0.50461071 0.11024914 0.1870162  0.09072123 0.05582016]
 [0.43830194 0.96826093 0.27877071 0.59200942 0.08394117]
 [0.68836464 0.93035003 0.51865816 0.00686488 0.49322245]
 [0.11783268 0.12467542 0.32138248 0.81138055 0.75993879]]


# Randint()

In [17]:
integer_random = np.random.randint(10,50,5)
print(integer_random)

[27 29 28 27 14]


In [18]:
my_array = np.array([ 10 , 12 , 14 , 16 , 20 , 25 ])
print (my_array)

[10 12 14 16 20 25]


In [19]:
print(my_array.ndim)
print(my_array.shape)

1
(6,)


In [20]:
for i in my_array:
    print (i)

10
12
14
16
20
25


In [21]:
integer_random = np.random.randint(1,11, size=(4,5))
print(integer_random)

[[5 2 2 3 2]
 [5 8 6 1 3]
 [1 2 6 3 8]
 [3 8 3 8 4]]


In [22]:
print(integer_random.ndim)
print(integer_random.shape)

2
(4, 5)


In [23]:
for i in integer_random:
    print(i)

[5 2 2 3 2]
[5 8 6 1 3]
[1 2 6 3 8]
[3 8 3 8 4]


In [24]:
for rows in integer_random:
    for cloumn in rows:
        print(cloumn)

5
2
2
3
2
5
8
6
1
3
1
2
6
3
8
3
8
3
8
4


# Append()

In [25]:
my_array = np.array(["Red", "Green", "Orange"])
print (my_array)

extended = np.append(my_array, "Yellow")
print(extended)

['Red' 'Green' 'Orange']
['Red' 'Green' 'Orange' 'Yellow']


In [26]:
my_array = np.array(["Red", "Green", "Orange"])
print (my_array)

extended = np.append(my_array, ["Yellow","Pink"])
print(extended)

['Red' 'Green' 'Orange']
['Red' 'Green' 'Orange' 'Yellow' 'Pink']


# Delete()

In [27]:
my_array = np.array(["Red", "Green", "Orange"])
print (my_array)

print("After deltion")
updated_array = np.delete(my_array,1)

print(updated_array)

['Red' 'Green' 'Orange']
After deltion
['Red' 'Orange']


In [28]:
my_array = np.array(["Red", "Green", "Orange"])
print (my_array)
print ("After deletion")
updated_array = np.delete(my_array, [ 1 , 2 ])
print (updated_array)

['Red' 'Green' 'Orange']
After deletion
['Red']


# Sorting Numpy Arrays

In [29]:
print ("unsorted array")
my_array = np.random.randint( 1 , 20 , 10 )
print (my_array)
print (" \n sorted array")
sorted_array = np.sort(my_array)
print (sorted_array)

unsorted array
[ 5 16 11  4  8 13 15 14 19 13]
 
 sorted array
[ 4  5  8 11 13 13 14 15 16 19]


In [30]:
print ("unsorted array")
my_array = np.random.randint( 1 , 20 , size = ( 4 , 6 ))
print (my_array)
print ("\Sorted array")
sorted_array = np.sort(my_array)
print (sorted_array)

unsorted array
[[16  3  4 19  4  6]
 [16  2 10  5 16 16]
 [ 2  6  7 12 12 14]
 [17 19 13  8 19 18]]
\Sorted array
[[ 3  4  4  6 16 19]
 [ 2  5 10 16 16 16]
 [ 2  6  7 12 12 14]
 [ 8 13 17 18 19 19]]


In [31]:
print ("unsorted array")
my_array = np.random.randint( 1 , 20 , 10 )
print (my_array)
print (" \n sorted array")
sorted_array = np.sort(my_array)
reverse_sorted = np.flipud(sorted_array)
print (reverse_sorted)

unsorted array
[15  8  4  8 15 10 10  2 16 17]
 
 sorted array
[17 16 15 15 10 10  8  8  4  2]


In [32]:
print ("one-dimensional array")
one_d_array = np.random.randint( 1 , 20 , 10 )
print (one_d_array)
print (" \n two-dimensional array")
two_d_array = one_d_array.reshape( 2 , 5 )
print (two_d_array)

one-dimensional array
[ 2  5  9 19  6 17 13  5 17 17]
 
 two-dimensional array
[[ 2  5  9 19  6]
 [17 13  5 17 17]]


In [33]:
print ("two-dimensional array")
two_d_array = np.random.randint( 1 , 20 , size = ( 4 , 6 ))
print (one_d_array)
print (" \n three-dimensional array")
three_d_array = np.reshape(two_d_array,( 3 , 4 , 2 ))
print (two_d_array)

two-dimensional array
[ 2  5  9 19  6 17 13  5 17 17]
 
 three-dimensional array
[[ 9  6  2 17 13  6]
 [16 18 14  4  7 10]
 [18 14 15 16 18  1]
 [16  5 12  3  1  5]]


# Indexing and Slicing NumPy Arrays

In [34]:
s = np.arange(1,11)
print(s)

[ 1  2  3  4  5  6  7  8  9 10]


In [35]:
print(s[1])

2


In [36]:
print(s[1:9])

[2 3 4 5 6 7 8 9]


In [37]:
print(s[:5])

print(s[5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [38]:
row1 = [ 10 , 12 , 13 ]
row2 = [ 45 , 32 , 16 ]
row3 = [ 45 , 32 , 16 ]
nums_2d = np.array([row1, row2, row3])
print (nums_2d[: 2 ,:])


[[10 12 13]
 [45 32 16]]


In [39]:
print (nums_2d[:,: 2 ])

[[10 12]
 [45 32]
 [45 32]]


In [40]:
print (nums_2d[ 1 :, 1 :])

[[32 16]
 [32 16]]


# mean()

In [41]:
my_array = np.array([ 2 , 4 , 8 , 10 , 12 ])
print (my_array)
print ("mean:")
print (np.mean(my_array))

[ 2  4  8 10 12]
mean:
7.2


In [42]:
my_array = np.random.randint( 1 , 20 , size = ( 2 , 3 ))
print (my_array)
print ("mean:")
print (np.mean(my_array, axis = 1 ))
print (np.mean(my_array, axis = 0 ))

[[19  2  8]
 [12  4  2]]
mean:
[9.66666667 6.        ]
[15.5  3.   5. ]


# Median

In [43]:
my_array = np.array([ 2 , 4 , 8 , 10 , 12 ])
print (my_array)
print ("median:")
print (np.median(my_array))

[ 2  4  8 10 12]
median:
8.0


In [44]:
my_array = np.random.randint( 1 , 20 , size = ( 3 , 5 ))
print (my_array)
print ("median:")
print (np.median(my_array, axis = 1 ))
print (np.median(my_array, axis = 0 ))

[[ 2  8 13  2 13]
 [11  6 17 16  3]
 [15 11 11  2  1]]
median:
[ 8. 11. 11.]
[11.  8. 13.  2.  3.]


# min()

In [45]:
my_array = np.array([ 2 , 4 , 8 , 10 , 12 ])
print (my_array)
print ("min value:")
print (np.amin(my_array))

[ 2  4  8 10 12]
min value:
2


In [46]:
my_array = np.random.randint( 1 , 20 , size = ( 3 , 4 ))
print (my_array)
print ("min:")
print (np.amin(my_array, axis = 1 ))
print (np.amin(my_array, axis = 0 ))

[[13  2 18  2]
 [ 7 14 12 18]
 [14  5 14  7]]
min:
[2 7 5]
[ 7  2 12  2]


# Max()

In [47]:
my_array = np.array([ 2 , 4 , 8 , 10 , 12 ])
print (my_array)
print ("max value:")
print (np.amax(my_array))

[ 2  4  8 10 12]
max value:
12


In [48]:
my_array = np.random.randint( 1 , 20 , size = ( 3 , 4 ))
print (my_array)
print ("max:")
print (np.amax(my_array, axis = 1 ))
print (np.amax(my_array, axis = 0 ))

[[ 9  1  2 19]
 [ 7  2  6 15]
 [ 4 14 12 12]]
max:
[19 15 14]
[ 9 14 12 19]


# unique() 

In [49]:
my_array =np.array([ 5 , 8 , 7 , 5 , 9 , 3 , 7 , 7 , 1 , 1 , 8 , 4 , 6 , 9 , 7 , 3 ])
unique_items = np.unique(my_array)
print (unique_items)

[1 3 4 5 6 7 8 9]


# sqrt() 

In [50]:
nums = [ 10 , 20 , 30 , 40 , 50 ]
np_sqr = np.sqrt(nums)
print (np_sqr)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


# log()

In [51]:
nums = [ 10 , 20 , 30 , 40 , 50 ]
np_log = np.log(nums)
print (np_log)

[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


# Exp()

In [52]:
nums = [ 10 , 20 , 30 , 40 , 50 ]
np_exp = np.exp(nums)
print (np_exp)

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
